[package]
name = "Ownership"
version = "1.0.0-beta.2"
type = "bin"
authors = ["Tisura"]

[dependencies]
chacha20 = { path = "../../substring/lib/" }
json_parser = { tag = "v0.4.0", git = "https://github.com/noir-lang/noir_json_parser" }
